/* Sonexa Game Studios — language picker.
   Each language is its own pre-rendered page (/br/, /de/, …) generated by
   tools/build-pages.py, so there is nothing to translate at runtime: the
   options are real links baked into the HTML. This only opens the menu, and
   remembers the visitor's choice so the logo always returns them to it. */
(() => {
  "use strict";

  const btn = document.getElementById("langBtn");
  const menu = document.getElementById("langMenu");
  if (!btn || !menu) return;

  const close = () => { menu.classList.remove("open"); btn.setAttribute("aria-expanded", "false"); };
  const open = () => { menu.classList.add("open"); btn.setAttribute("aria-expanded", "true"); };

  btn.addEventListener("click", (e) => {
    e.stopPropagation();
    menu.classList.contains("open") ? close() : open();
  });

  document.addEventListener("click", (e) => {
    if (!e.target.closest(".nav-lang")) close();
  });

  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && menu.classList.contains("open")) { close(); btn.focus(); }
  });

  // Roving focus through the list, so the picker is usable from the keyboard.
  menu.addEventListener("keydown", (e) => {
    const links = [...menu.querySelectorAll("a")];
    const i = links.indexOf(document.activeElement);
    if (e.key === "ArrowDown" || e.key === "ArrowUp") {
      e.preventDefault();
      const next = e.key === "ArrowDown" ? i + 1 : i - 1;
      links[(next + links.length) % links.length].focus();
    }
  });
  btn.addEventListener("keydown", (e) => {
    if (e.key === "ArrowDown") { e.preventDefault(); open(); menu.querySelector("a")?.focus(); }
  });
})();
