#!/usr/bin/env python3
"""Generate one real HTML page per language from index.html + i18n/*.json.

GitHub Pages is a static host with no rewrite rules, so a URL like /br/ has to
be an actual folder with an actual index.html in it. That is also the better
outcome: each language is a fully translated page that search engines can crawl
and that works with JavaScript switched off, rather than text swapped in later.

    python tools/build-pages.py

English stays at the site root. Every other language is written to its folder
from i18n/languages.json, overwriting whatever was there.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAGE = ROOT / "index.html"
I18N = ROOT / "i18n"
GENERATED_MARK = "<!-- generated by tools/build-pages.py — edit index.html instead -->"


def flatten(obj, prefix="", out=None):
    out = {} if out is None else out
    for key, value in obj.items():
        full = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            flatten(value, full, out)
        else:
            out[full] = value
    return out


def alternates(config, active_path):
    """canonical + hreflang block, identical logic for every page."""
    base = config["baseUrl"].rstrip("/")
    url = lambda p: f"{base}/{p}/" if p else f"{base}/"
    lines = [f'<link rel="canonical" href="{url(active_path)}">']
    for lang in config["languages"]:
        lines.append(f'  <link rel="alternate" hreflang="{lang["hreflang"]}" href="{url(lang["path"])}">')
    lines.append(f'  <link rel="alternate" hreflang="x-default" href="{url("")}">')
    return "\n".join(lines)


def translate(markup, strings):
    missing = []

    def swap_element(match):
        open_tag, tag, _body, close_tag = match.groups()
        key = re.search(r'data-i18n="([^"]+)"', open_tag).group(1)
        if key not in strings:
            missing.append(key)
            return match.group(0)
        return f"{open_tag}{strings[key]}{close_tag}"

    markup = re.sub(
        r'(<(\w+)[^>]*\bdata-i18n="[^"]+"[^>]*>)(.*?)(</\2>)',
        swap_element,
        markup,
        flags=re.S,
    )

    def swap_attr(match):
        attr, key, _old = match.groups()
        if key not in strings:
            missing.append(key)
            return match.group(0)
        value = strings[key].replace('"', "&quot;")
        return f'data-i18n-attr="{attr}:{key}" {attr}="{value}"'

    markup = re.sub(r'data-i18n-attr="([^:]+):([^"]+)"\s+\1="([^"]*)"', swap_attr, markup)
    return markup, missing


def esc(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace('"', "&quot;")


def main():
    config = json.loads((I18N / "languages.json").read_text(encoding="utf-8"))
    source = PAGE.read_text(encoding="utf-8")
    base = config["baseUrl"].rstrip("/")
    problems = 0

    for lang in config["languages"]:
        code, path = lang["code"], lang["path"]
        page_url = f"{base}/{path}/" if path else f"{base}/"

        if code == "en":
            out_path, markup, strings = PAGE, source, {}
        else:
            data = I18N / f"{code}.json"
            if not data.exists():
                print(f"  {code}: no {data.name}, skipped", file=sys.stderr)
                problems += 1
                continue
            strings = flatten(json.loads(data.read_text(encoding="utf-8")))
            markup, missing = translate(source, strings)
            if missing:
                print(f"  {code}: {len(missing)} key(s) fell back to English: {', '.join(sorted(set(missing))[:4])}")
            out_path = ROOT / path / "index.html"

        # per-page head: language, canonical/hreflang, and the social preview URL
        markup = re.sub(r'<html lang="[^"]*"', f'<html lang="{code}"', markup, count=1)
        markup = re.sub(
            r"<!-- i18n:alternates -->.*?<!-- /i18n:alternates -->",
            lambda _m: f"<!-- i18n:alternates -->{alternates(config, path)}\n  <!-- /i18n:alternates -->",
            markup,
            flags=re.S,
        )
        markup = re.sub(r'(<meta property="og:url" content=")[^"]*(")', rf"\g<1>{page_url}\g<2>", markup)

        # the picker is baked into every page: no extra request, no list to drift,
        # and the options stay real links if JavaScript never runs
        options = []
        for other in config["languages"]:
            href = f"/{other['path']}/" if other["path"] else "/"
            on = ' class="on" aria-current="true"' if other["code"] == code else ""
            options.append(
                f'<li><a href="{href}" hreflang="{other["hreflang"]}" lang="{other["code"]}"{on}>{other["name"]}</a></li>'
            )
        markup = re.sub(
            r"<!-- i18n:picker -->.*?<!-- /i18n:picker -->",
            lambda _m: "<!-- i18n:picker -->" + "".join(options) + "<!-- /i18n:picker -->",
            markup,
            flags=re.S,
        )
        markup = re.sub(
            r"<!-- i18n:current -->.*?<!-- /i18n:current -->",
            lambda _m: f"<!-- i18n:current -->{lang['name']}<!-- /i18n:current -->",
            markup,
            flags=re.S,
        )

        if code != "en":
            for key, pattern in (
                ("meta.title", r"(<title>).*?(</title>)"),
                ("meta.description", r'(<meta name="description" content=").*?(")'),
                ("meta.ogDescription", r'(<meta property="og:description" content=").*?(")'),
            ):
                if key in strings:
                    markup = re.sub(pattern, rf"\g<1>{esc(strings[key])}\g<2>", markup, flags=re.S)
            markup = markup.replace("<body>", f"<body>\n  {GENERATED_MARK}", 1)
            out_path.parent.mkdir(parents=True, exist_ok=True)

        out_path.write_text(markup, encoding="utf-8")
        label = "/" if not path else f"/{path}/"
        print(f"  {code:<7} -> {label}")

    # sitemap + robots, generated here so they can never fall out of step with
    # the language list or the domain
    urls = []
    for lang in config["languages"]:
        loc = f"{base}/{lang['path']}/" if lang["path"] else f"{base}/"
        alts = "".join(
            f'\n    <xhtml:link rel="alternate" hreflang="{o["hreflang"]}" '
            f'href="{base}/{o["path"]}/" />' if o["path"] else
            f'\n    <xhtml:link rel="alternate" hreflang="{o["hreflang"]}" href="{base}/" />'
            for o in config["languages"]
        )
        urls.append(f"  <url>\n    <loc>{loc}</loc>{alts}\n  </url>")
    for policy in ("privacy/drumhit", "privacy/tower-to-space", "privacy/wobbins-hide-and-hue"):
        urls.append(f"  <url>\n    <loc>{base}/{policy}/</loc>\n  </url>")

    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
        + "\n".join(urls)
        + "\n</urlset>\n",
        encoding="utf-8",
    )
    (ROOT / "robots.txt").write_text(
        f"User-agent: *\nAllow: /\n\nSitemap: {base}/sitemap.xml\n", encoding="utf-8"
    )
    print(f"sitemap.xml ({len(urls)} urls) + robots.txt written")

    print(f"{len(config['languages'])} pages written" + (f", {problems} skipped" if problems else ""))
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
